FROM php:7.4-cli

RUN apt-get update && apt-get install -y \
    build-essential libzip-dev libpng-dev libjpeg62-turbo-dev \
    libfreetype6-dev locales zip jpegoptim optipng pngquant gifsicle \
    supervisor vim unzip git curl && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir /app

RUN docker-php-ext-install gd zip exif pcntl

WORKDIR /var/log/supervisor

RUN groupadd -g 1000 worker && \
    useradd -u 1000 -ms /bin/bash -g worker worker && \
    chown worker:worker /var/log/supervisor

COPY --chown=worker:worker . /app

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisor/supervisord.conf"]
