version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisor/conf.d/:/etc/supervisor/conf.d/

  web:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${APP_PORT}:80"

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        volume:
          nocopy: true
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  npm:
    image: node:alpine
    working_dir: /app
    entrypoint: npm
    volumes:
      - ./:/app

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8090:8080

volumes:
  dbdata:
