version: '3.7'

services:

  app:
    image: bitnami/laravel:7
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "3001:3000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        volume:
          nocopy: true
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8090:8080

volumes:
  dbdata:
